name: CI

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]
  workflow_dispatch:

jobs:
  tests:
    name: "Test and lint for Python 3.9"
    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
          python-version: "3.9"
      - name: "Install dependencies"
        working-directory: model_detection
        run: |
          python -VV
          python -m site
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install --upgrade -r requirements/test_requirements.txt
      - name: "Run tests"
        working-directory: model_detection
        run: python -m pytest tests/
      - name: "Run linters (isort, black and flake8)"
        working-directory: model_detection
        run: pre-commit run --all-files
